export default [
    {
        id: 1,
        img:'https://cdn.pixabay.com/photo/2019/08/13/08/48/bucuresti-4402855_960_720.jpg',
        mainFeature:'Diversity',
        country:'Romania',
        googleMaps:'https://goo.gl/maps/S9MX7ny75qCTXyaB8',
        city:'Bucuresti',
        period: '04 Feb, 2022 - 22 Feb, 2022',
        description:'Bucharest is the capital and largest city of Romania, as well as its cultural, industrial, and financial centre. It is located in the southeast of the country, on the banks of the Dâmbovița River, less than 60 km (37.3 mi) north of the Danube River and the Bulgarian border. In recent years, the city has been experiencing an economic and cultural boom. It is one of the fastest-growing high-tech cities in Europe, according to the Financial Times, CBRE, TechCrunch, and others. UiPath, a global startup founded in Bucharest, has reached over $35 billion in valuation. Since 2019, Bucharest hosts the largest high tech summit in Southeast Europe (Romania Blockchain Summit).',
    },
    {
        id: 2,
        img:'https://dspbv.ro/wp-content/uploads/2020/10/Brasov.jpg',
        mainFeature:'Nature',
        country:'Romania',
        googleMaps:'https://goo.gl/maps/kBw9pdQnQH4cbcm47',
        city:'Brasov',
        period: '12 Jan, 2021 - 24 Jan, 2021',
        description:'Brașov is a city in Transylvania, Romania and the administrative centre of Brașov County. According to the latest Romanian census (2011), Brașov has a population of 253,200 making it the 7th most populous city in Romania. The metropolitan area is home to 382,896 residents. Brașov is located in the central part of the country, about 166 km (103 mi) north of Bucharest and 380 km (236 mi) from the Black Sea. It is surrounded by the Southern Carpathians and is part of the historical region of Transylvania. Historically, the city was the center of the Burzenland, once dominated by the Transylvanian Saxons, and a significant commercial hub on the trade roads between Austria and Turkey. It is also where the national anthem of Romania was first sung.',        
    },
    {
        id: 3,
        img: 'https://urlaub-in-rumänien.de/wp-content/uploads/2017/10/piata_unirii_oradea.jpg',
        mainFeature:'Freedom',
        country:'Romania',
        googleMaps:'https://goo.gl/maps/qhEkCNZ1zVHTtmTq7',
        city:'Oradea',
        period: '22 Jul, 2019 - 29 Jul, 2019',
        description:'Oradea is a city in Romania, located in Crișana, a sub-region of Transylvania. Seat of the Bihor county, Oradea is one of the most important economic, social and cultural centers in the western part of Romania. The city is located in the north-west of the country, nestled between hills on the Crișana plain, on the banks of the river Crișul Repede, that divides the city into almost equal halves. Located about 10 km (6.2 mi) from Borș, one of the most important crossing points on Romania is border with Hungary, Oradea ranks tenth in size among Romanian cities. It covers an area of 11,556 hectares (28,560 acres), in an area of contact between the extensions of the Apuseni Mountains and the Crișana-Banat extended plain. Oradea enjoys a high standard of living relative to other Romanian cities and ranks among the most livable cities in the country. The city is also a strong industrial center in the region, hosting some of Romania is largest companies. Besides its status as an economic hub, Oradea boasts a rich Art Nouveau architectural heritage and is a member of the Réseau Art Nouveau Network and the Art Nouveau European Route, Timișoara also being part of the latter', 
    },
    {
        id: 4,
        img:'https://www.stiridecluj.ro/files/images/177/969970be507d68de871f34f6a14e6f85.jpg',
        mainFeature:'Respect',
        country:'Romania',
        googleMaps:'https://goo.gl/maps/t4eH5xrgQdkMUirc7',
        city:'Cluj',
        period: '14 Aug, 2020 - 30 Aug, 2020',
        description:'Clujul is the fourth-most populous city in Romania. Geographically, it is roughly equidistant from Bucharest (445 kilometres (277 miles)), Budapest (461 km (286 mi)) and Belgrade (483 km (300 mi)). Located in the Someșul Mic river valley, the city is considered the unofficial capital of the historical province of Transylvania. From 1790 to 1848 and from 1861 to 1867, it was the official capital of the Grand Principality of Transylvania.', 
    },   
]